require 'rake/clean'


directory 'tmp'

desc "Cria a página html"
task :html => ['tmp']do

  sh "claat export -o tmp/ git.md"

  puts "Criando conteúdo em tmp/"
  puts "Execute rake local para levantar servidor localmente"

end

desc 'atualiza código gerado'
task :update do
  sh "claat update -o tmp/ git.md"
end

file 'tmp/git-exemplo1/index.html'

desc 'Serve localmente arquivo gerado'
task 'serve' do
  Dir.chdir('tmp/git-exemplo1') do
    sh "claat serve"
  end
end

CLEAN.include("tmp")

task :default => ['html']
