
directory 'tmp'

desc "Cria a página html"
task :html => ['tmp']do

  sh "claat export -o tmp/ git.md"

  puts "Criando conteúdo em tmp/"
  puts "Execute rake local para levantar servidor localmente"

end

file 'tmp/git-exemplo1/index.html'

desc 'Serve localmente arquivo gerado'
task 'serve' do
  Dir.chdir('tmp/git-exemplo1') do
    sh "claat serve"
  end
end
